spring:
  aplication:
    name: Security JWT - Header
  h2:
    console:
      enabled: true
      path: /h2-ui
  datasource:
    url: jdbc:h2:file:./testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        enable_lazy_load_no_trans: true
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8081

example:
  jwt:
    secret: keyProject
    expirationMs: 900000
    cookieName: tokenApi